version: '3'  # Prefer newer version for better compatibility

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Set GPU visibility (use 'all' or specific GPU id)
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Optional, adjust as needed


